server:
   # 0 表示随机端口
   port: 0
   
spring:
   application:
      name: blog-index
      
eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:8000/eureka
         
# 设定 feign.hystrix.enabled=true，那么Feign将用断路器包装所有的控制层方法
feign:
  hystrix:
    enabled: true