server:
   port: 80
   
spring:
   application:
      name: blog-zuul
      
eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:8000/eureka

# 简单路由配置
zuul:
   #    将敏感头设置在 zuul 下，表示对所有的路由的有效
   #    设置要过滤的敏感头， 设置空值可以取消过滤所有的头域字段 ==》 不过滤
   sensitiveHeaders: 
   routes:
      # 用户网元地址
      blog-user:
         path: /user/**
       # 文章网元地址
      blog-article:
         path: /article/**
       # 门户网元地址==》默认路由
      blog-index:
         path: /**
      # 默认路由